[project]
name = "houses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.12.7",
    "textual>=5.1.1",
]

[dependency-groups]
dev = [
    "textual-dev>=1.7.0",
]
